baseurl = "https://www.emanuelboderash.com/"
title = "@emanuelboderash"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"
relativeURLS = true

paginate = 20
canonifyurls = true

pygmentsstyle = "monokailight"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

#disqusShortname = "yourdiscussshortname"

[params]
    author = "Emanuel Boderash"
    info = "Software Engineer"
    description = "Personal Website"
    keywords = "blog,developer,personal,ctf,writeup,writeups,ebodera,emanuel,boderash,emanuelboderash"
    avatarurl = "images/avatar.jpg"

    # favicon_32 = "/img/favicon-32x32.png"
    # favicon_16 = "/img/favicon-16x16.png"

    #footercontent = "Enter a text here."

    hidecredits = true
    hidecopyright = true

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Twitter"
    icon = "fa fa-twitter fa-2x"
    weight = 1
    url = "https://twitter.com/emanuelboderash"
[[params.social]]
    name = "Instagram"
    icon = "fa fa-instagram fa-2x"
    weight = 2
    url = "https://instagram.com/emanuelboderash"
# [[params.social]]
#     name = "Snapchat"
#     icon = "fa fa-snapchat-ghost fa-2x"
#     weight = 3
#     url = "https://snapchat.com/add/emanuelboderash"
[[params.social]]
    name = "YouTube"
    icon = "fa fa-youtube-play fa-2x"
    weight = 3
    url = "https://www.youtube.com/channel/UCD5BCi98vojb8gD9iMy0Lxw"
[[params.social]]
    name = "Telegram"
    icon = "fa fa-telegram fa-2x"
    weight = 4
    url = "https://t.me/emanuelboderash"
[[params.social]]
    name = "Discord"
    icon = "fa fa-discord-alt fa-2x"
    weight = 5
    url = "https://discord.com/users/507747105763360778"
# [[params.social]]
#     name = "LinkedIn"
#     icon = "fa fa-linkedin fa-2x"
#     weight = 5
#     url = "https://linkedin.com/in/emanuelboderash"
# [[params.social]]
#     name = "Keybase"
#     icon = "fa fa-keybase fa-2x"
#     weight = 6
#     url = "https://keybase.io/emanuelboderash"
[[params.social]]
    name = "Calendly"
    icon = "fa fa-calendar fa-2x"
    weight = 6
    url = "https://calendly.com/emanuelboderash"
[[params.social]]
    name = "Github"
    icon = "fa fa-github fa-2x"
    weight = 7
    url = "https://github.com/emanuelboderash"
[[params.social]]
    name = "Medium"
    icon = "fa fa-medium fa-2x"
    weight = 8
    url = "https://medium.com/@emanuelboderash"
[[params.social]]
    name = "Notion"
    icon = "fa fa-cube fa-2x"
    weight = 9
    url = "https://emanuelboderash.notion.site/6dd62dd1699c435e86a20bd000dc4619?v=76d37caa61364d11a687924d76ba9a38"
[[params.social]]
    name = "Cyber"
    icon = "fa fa-paint-brush fa-2x"
    weight = 10
    url = "https://oncyber.io/@0x1eb5f6d2388b2dee3505334e4aeb96728a757b2b"
[[params.social]]
    name = "Goodreads"
    icon = "fa fa-book fa-2x"
    weight = 11
    url = "https://www.goodreads.com/emanuelboderash"
# [[params.social]]
#     name = "Spotify"
#     icon = "fa fa-spotify fa-2x"
#     weight = 11
#     url = "https://open.spotify.com/user/vuaizj773768ct2l22f1p6wag"
# [[params.social]]
#     name = "Soundcloud"
#     icon = "fa fa-soundcloud fa-2x"
#     weight = 11
#     url = "https://soundcloud.com/emanuelboderash"
# [[params.social]]
#     name = "Letterboxd"
#     icon = "fa fa-film fa-2x"
#     weight = 11
#     url = "https://letterboxd.com/ebodera"
[[params.social]]
    name = "Lifting Database"
    icon = "fa fa-trophy fa-2x"
    weight = 12
    url = "https://usapl.liftingdatabase.com/lifters-view?id=47258"
[[params.social]]
    name = "Strike"
    icon = "fa fa-bitcoin fa-2x"
    weight = 13
    url = "https://strike.me/emanuelboderash"
[[params.social]]
    name = "Ethereum"
    icon = "fa fa-ethereum fa-2x"
    weight = 14
    url = "https://emanuelboderash.eth.xyz"
# [[params.social]]
#     name = "Bitcoin"
#     icon = "fa fa-bitcoin fa-2x"
#     weight = 15
#     url = "/btc/"
# [[params.social]]
#     name = "Ethereum"
#     icon = "fa fa-ethereum fa-2x"
#     weight = 16
#     url = "/eth/"
# [[params.social]]
#     name = "Monero"
#     icon = "fa fa-monero fa-2x"
#     weight = 17
#     url = "/xmr/"
# [[params.social]]
#     name = "PayPal"
#     icon = "fa fa-paypal fa-2x"
#     weight = 15
#     url = "https://paypal.me/eboderas"
# [[params.social]]
#     name = "Venmo"
#     icon = "fa fa-money fa-2x"
#     weight = 16
#     url = "https://venmo.com/emanuelboderash"
[[params.social]]
    name = "Cash App"
    icon = "fa fa-usd fa-2x"
    weight = 15
    url = "https://cash.app/$emanuelboderash"
# [[params.social]]
#     name = "Patreon"
#     icon = "fa fa-patreon fa-2x"
#     weight = 18
#     url = "https://patreon.com/emanuelboderash"

# Menu links
[[menu.main]]
    name = "Projects"
    weight = 1
    url = "/projects/"
[[menu.main]]
    name = "Write-ups"
    weight = 2
    url = "/writeups/"
[[menu.main]]
    name = "Resume"
    weight = 3
    url = "https://resume.emanuelboderash.com"
